language: php
php:
  - '7.0'
settings:
  colors: true
  memory_limit: 1024M
before_script:
  - composer install
script:
  - mkdir -p build/logs
- vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  - travis_retry php vendor/bin/php-coveralls