language: php

php:
  - '7.2'

# You can delete cache using travis-ci web interface
cache:
  directories:
  - vendor
  - $HOME/.cache/composer

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls
